# logging
log_dir: "/home/ASRL/doppler_odom_utias/temp_boreas/sep29_train1_seq1"

# dataset
dataset: "boreas_aeva"
dataset_options:
  all_sequences: false
  root_path: "/home/ASRL/steam_icp/data/boreas-aeries/"
  sequence: "2023_02_15_1"
  init_frame: 0
  last_frame: 100000
  active_sensors: [true]

# doppler calib
doppler_options:
  root_path: "/home/ASRL/doppler_odom/sensor_config/boreas/"
  azimuth_res: 0.00349066
  azimuth_start: -0.872665
  azimuth_end: 0.872665
  num_rows: 80
  num_cols: 501

# odometry
odometry: "doppler_filter"
odometry_options:
  ransac_max_iter: 20
  ransac_thres: 0.2
  min_dist_lidar_center: 20.0 
  max_dist_lidar_center: 150.0 
  integration_steps: 100
  P0inv: [1e6, 1e6, 1e6, 1e8, 1e8, 1e8]
  Qkinv: [124.097194, 852.430330017, 448.704299478, 1128.19639192, 1230.02908934, 11316.9459369]
  Qzinv: [0.0, 0.0, 0.0, 14274.3037743, 11121.0286591, 0.0]
  

